'use strict';
/* ==========================================================================
   OpsPulse Decision Engine — runner / CLI
   --------------------------------------------------------------------------
     node engine/run.js
   Runs the full pipeline, ASSERTS the ExecutiveBrief against the schema
   contract, prints a run report, and emits the browser artifact
   assets/brief.data.js (window.OPSPULSE_BRIEF) that the frozen Decision Feed
   renders. No network. Deterministic.
   ========================================================================== */

const fs = require('fs');
const path = require('path');
const { run } = require('./orchestrator');
const { validateBrief } = require('./schema');

(async () => {
  const { brief, run: info } = await run();

  // ── assert the contract ───────────────────────────────────────────────
  const v = validateBrief(brief);
  if (!v.ok) {
    console.error('\n✖ ExecutiveBrief FAILED schema validation:\n');
    v.errors.forEach((e) => console.error('   - ' + e));
    process.exit(1);
  }

  // ── run report ────────────────────────────────────────────────────────
  const s = info.stats, t = info.timings_ms;
  console.log('\n  OpsPulse Decision Engine — run report');
  console.log('  ' + '─'.repeat(52));
  console.log(`  raw records ingested : ${s.raw_records}`);
  console.log(`  normalized signals   : ${s.normalized}`);
  console.log(`  anomalies flagged    : ${s.anomalies_flagged}  (|z| ≥ ${s.thresholds.HIGH_Z})`);
  console.log(`  insights built       : ${s.insights_built}`);
  console.log(`  timings (ms)         : ing=${t.ingestion} detect=${t.detection} rc+rec=${t.rootcause_recommendation} exec=${t.exec_summary}`);
  console.log('  ' + '─'.repeat(52));
  console.log(`  ROLLUP  total_revenue_at_risk : $${brief.rollup.total_revenue_at_risk.toLocaleString()}`);
  console.log(`          top_3_ids             : ${brief.rollup.top_3_ids.join(', ')}`);
  console.log('  ' + '─'.repeat(52));
  brief.insights.forEach((i) => {
    const held = i.status === 'held_for_review' ? '  ⟨HELD: conf ' + i.why.confidence + '⟩' : '';
    console.log(`  [${String(i.severity_score).padStart(2)}] ${i.signal_type.padEnd(14)} conf ${i.why.confidence}  $${(i.expected_impact.revenue_at_risk_usd / 1000).toFixed(0)}k  ${i.insight_id}${held}`);
  });
  console.log('  ' + '─'.repeat(52));

  // ── emit browser artifact ─────────────────────────────────────────────
  const outPath = path.join(__dirname, '..', 'assets', 'brief.data.js');
  const banner =
    '/* AUTO-GENERATED by engine/run.js — do not edit by hand.\n' +
    '   Run `node engine/run.js` to regenerate. The frozen Decision Feed reads window.OPSPULSE_BRIEF. */\n';
  const body = 'window.OPSPULSE_BRIEF = ' + JSON.stringify(brief, null, 2) + ';\n' +
    'if (typeof module !== "undefined" && module.exports) module.exports = window.OPSPULSE_BRIEF;\n';
  fs.writeFileSync(outPath, banner + body);
  console.log('  ✔ schema valid · wrote assets/brief.data.js\n');
})().catch((e) => { console.error(e); process.exit(1); });
